# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fbff035409532251c132081a59058cd1b6b45ccc162f7a9c4119ef3695504896a8eed5db5bedd3307741fdb13cf2d77f9e841b90a65f725580f4c2a72b36e5e

test:
  secret_key_base: 44485dfe62fed7805902a40e25118f048115c0150c1deb286eda976bd5f6dbb0e6259054467cab2af0599366c3458110c8eab4fba826ef4d98053f6e9c27d69e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
