# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b538505e3933071753d1e893104afdae967b9eb896c3fd1f45734afb0e8782f1853a6fffb31363b9c8fd1ce5be0d172b29822d08892e8197df570c78f8788e6

test:
  secret_key_base: 5b398635389c7ac1094b0e30edf81b6323138dd611a9c8344cd5ed76e90c49828e856e89d223a9a78f21a86cca32229ab920fd642238d778288461391f5cfc74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
